# # - name: loop through hostnames
# #   hosts: localhost
# - name: Call post role
#   hosts: localhost
#   gather_facts: false
#   tasks:
#     - name: Include post role
#       import_role:
#         name: post



---
- name: Load and Print JSON Data
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Load JSON data
      slurp:
        path: 'C:\Users\pilla\desktop\DeVops_Practice\Ansible\data.json'
      register: json_data

    - name: Convert JSON data to string
      set_fact:
        json_string: "{{ json_data.content | b64decode | from_json }}"

    - name: Print JSON data
      debug:
        var: json_string



