# # - name: loop through hostnames
# #   hosts: localhost
# - name: Call post role
#   hosts: localhost
#   gather_facts: false
#   tasks:
#     - name: Include post role
#       import_role:
#         name: post



# ---
# - name: Load and Print JSON Data
#   hosts: localhost
#   gather_facts: false
#   tasks:
#     - name: Load JSON data
#       slurp:
#         path: 'data.json'
#       register: json_data

#     - name: Convert JSON data to string
#       set_fact:
#         json_string: "{{ json_data.content | b64decode | from_json }}"

#     # - name: Print JSON data
#     #   debug:
#     #     msg: "{{ item.item.result.output }}"
#     #   loop: "{{ json_string }}"

#     - name: Extract result output values
#       set_fact:
#         result_outputs: "{{ json_string | map(attribute='item.result') | list }}"

#     - name: Print result output values
#       debug:
#         var: result_outputs

---
- name: Modify ansible_facts.output
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Set input JSON
      set_fact:
        input_data:
          "changed": false
          "ansible_facts":
            "output":
              - - >
                  {"timestamp": "20","host":"12"}
                - null
              - - >
                  {"timestamp": "20","host":"12"}
                - null
              - - null
                - "msg": "this is my node"
                  "issue": "connect"
                  "details": {}
              - - null
                - "msg": "this is my node"
                  "issue": "connect"
                  "details": {}
          "ansible_log": false

    - name: Remove null values from JSON
      set_fact:
        json_data: "{{ input_data | remove_null_values_and_empty_strings_in_arrays }}"

    - name: Print JSON
      debug:
        msg: "{{ json_data }}"

    - name: Define filter
      filter:
        name: remove_null_values_and_empty_strings_in_arrays
        function:
          def remove_null_values_and_empty_strings_in_arrays(json_data):
            """Removes null values and empty strings from arrays in a JSON object.

            Args:
              json_data: The JSON object to remove null values and empty strings from.

            Returns:
              A new JSON object with the null values and empty strings removed.
            """

            output = {}
            for key, value in json_data.items():
              if value is not None:
                if isinstance(value, list):
                  output[key] = [item.strip() for item in value if item is not None and len(item.strip()) > 0]
                else:
                  output[key] = value
              else:
                output[key] = None
            return output







