
#Locla Variables > Global Variables
- name: variables
  hosts: all
  vars:
    URL: paly.google.com
  tasks:
    - name: Print URL
      ansible.builtin.debug:
        msg: the value of Url is {{ URL }}

    - name: Print URL
      ansible.builtin.debug:
        msg: the value of Url is {{ URL }}

    - name: Print URL
      ansible.builtin.debug:
        msg: the value of Url is {{ AURL }}
      vars:
        URL: task.google.com

