- name: Use _nodename from post main.yml
  set_fact:
    nodenames: "{{ _nodename }}"
  when: inventory_hostname == 'localhost'

- name: Print _nodename
  debug:
    var: nodenames
  when: inventory_hostname == 'localhost'