- name: Use _nodename from post main.yml
  set_fact:
    #nodenames: "{{ _nodename }}"
    params: "{{ params | dict2items | rejectattr('value', 'equalto', null) | items2dict }}"

- name: Print _nodename
  debug:
    var: params
