- name: Use _nodename from post main.yml
  set_fact:
    #nodenames: "{{ _nodename }}"
    params: "{{ tasks_params }}"

- name: Remove null values from params
  set_fact:
    params: "{{ params | default({}) }}"
  when: params is not defined or (params.version is not defined and params.scope is not defined)

- name: Print _nodename
  debug:
    var: params
