- name: Use _nodename from post main.yml
  set_fact:
    nodenames: "{{ _nodename }}"
    params: "{{ tasks_params | default(omit) }}"


- name: Print _nodename
  debug:
    var: nodenames,params
  #when: inventory_hostname == 'localhost'
