- name: Use _nodename from post main.yml
  set_fact:
    #nodenames: "{{ _nodename }}"
    params: "{{ tasks_params }}"

- name: Remove null values from params
  set_fact:
    params: "{{ params | omit('scope', 'version') }}"
  when: params is defined and (params.version is not defined or params.scope is not defined)

- name: Print _nodename
  debug:
    var: params
