- name: Use _nodename from post main.yml
  set_fact:
    #nodenames: "{{ _nodename }}"
    params: "{{ tasks_params }}"

- name: Remove null values from params
  set_fact:
    params: "{{ params | default({}) | dict2items | rejectattr('value', 'equalto', null) | items2dict }}"

- name: Print _nodename
  debug:
    var: params
