- name: Use _nodename from post main.yml
  set_fact:
    nodenames: "{{ _nodename }}"
    scope:     "{{ scope | default(omit) }}"
  #when: inventory_hostname == 'localhost'

- name: Print _nodename
  debug:
    var: nodenames,scope,version
  #when: inventory_hostname == 'localhost'
