- name: Use _nodename from post main.yml
  set_fact:
    nodenames: "{{ _nodename }}"
    scope:     "{{ tasks_params }}"
  #when: inventory_hostname == 'localhost'

- name: Print _nodename
  debug:
    var: nodenames,scope
  #when: inventory_hostname == 'localhost'
