# - name: Include variables from var.yml
#   include_vars:
#     file: vars/var.yml
- name: Set hostname variable
  include_role:
    name: common
    tasks_from: file
  vars:
    hostname_list:
      - host1
      - host2
      - host3
  vars: 
    _nodename: "{{ item }}"
  loop: "{{ hostname_list[0:5] | upper}}"
  loop_control:
    loop_var: item


#     - name: Use hostname variable in another task
#       debug:
#         msg: "Processing hostname: {{ current_hostname }}"
# - name: Include variables from var.yml
#   include_vars:
#     file: vars/var.yml

# - name: Use variables from var.yml
#   debug:
#     var: hostname_list

