- name: Loop through hostnames and include common role
  # hosts: localhost
  # gather_facts: false

  vars:
    hostname_list:
      - host1
      - host2
      - host3

  tasks:
    - name: Include common role
      include_role:
        name: common
          tasks_from: file 
      loop: "{{ hostname_list }}"
      loop_control:
        loop_var: _nodename

