- name: execute the file task
  include_role:
    name: common
    tasks_from: file
    vars:
      hostname_list:
        - host1
        - host2
        - host3
      hostname: "{{ _nodename[0:5] }}"
  loop: "{{ hostname_list }}"
  loop_control:
    loop_var: _nodename
