- name: Include variables from var.yml
  include_vars:
    file: vars/var.yml

# - name: Set hostname variable
#   include_role:
#     name: common
#     tasks_from: file
#   loop: "{{ hostname_list }}"
#   loop_control:
#     loop_var: item
#   vars:
#     _nodename: "{{ item[0:5] | upper }}"

- name: Set scope variable
  include_role:
    name: common
    tasks_from: file
  vars:
    tasks_params:
      action: "{{ action }}"
      version: "{{ version }}"
      scope: "{{ scope }}"


