- name: Include variables from var.yml
  include_vars:
    file: vars/var.yml

- name: Set hostname variable
  include_role:
    name: common
    tasks_from: file
  vars:
    _nodename: "{{ item[0:5] | upper }}"
  loop: "{{ hostname_list }}"
  #loop: "{{ hostname_list.split(',') if ',' in hostname_list else [hostname_list] }}"
  loop_control:
    loop_var: item

- name: Set scope variable
  include_role:
    name: common
    tasks_from: file
  vars:
    scope: "{{ scope | default }}"


#     - name: Use hostname variable in another task
#       debug:
#         msg: "Processing hostname: {{ current_hostname }}"
# - name: Include variables from var.yml
#   include_vars:
#     file: vars/var.yml

# - name: Use variables from var.yml
#   debug:
#     var: hostname_list

