- name: assign a var
  include_role:
    name: common
    tasks_from: file 
  vars:
    hostname_list:
      - host1
      - host2
      - host3

- name: Set hostname fact
  loop: "{{ hostname_list }}"
  loop_control:
    loop_var: _nodename
