- name: Include variables from var.yml
  include_vars:
    file: vars/var.yml

- name: Set hostname variable
  include_role:
    name: common
    tasks_from: file
  vars: 
    _nodename: "{{ item }}"
  loop: "{{ hostname_list }}"
  loop_control:
    loop_var: item


#     - name: Use hostname variable in another task
#       debug:
#         msg: "Processing hostname: {{ current_hostname }}"
# - name: Include variables from var.yml
#   include_vars:
#     file: vars/var.yml

# - name: Use variables from var.yml
#   debug:
#     var: hostname_list

