- name: Include variables from var.yml
  include_vars:
    file: vars/var.yml

- name: Set hostname variable
  include_role:
    name: common
    tasks_from: file
  vars:
    tasks_params:
      action: "{{ action }}"
      version: "{{ version | default('latest') }}"
      scope: "{{ scope }}"
    _nodename: "{{ item }}"
  loop: "{{ hostname_list }}"
  loop_control:
    loop_var: item
# - name: Set scope variable
#   include_role:
#     name: common
#     tasks_from: file
#   vars:
#     tasks_params:
#       action: "{{ action }}"
#       version: "{{ version }}"
#       scope: "{{ scope }}"

- name: Set hostname runing
  include_role:
    name: common
    tasks_from: result
  vars:
    tasks_params:
      action: "{{ action }}"
      version: "{{ version | default('latest') }}"
      scope: "{{ scope }}"
    hostname: "{{ item }}"
  loop: "{{ hostname_list }}"
  loop_control:
    loop_var: item