# - name: Loop through hostnames and assign to variables
#   vars:
#     hostname_list:
#       - host1
#       - host2
#       - host3
#   tasks:
#     - name: Set hostname variable
#       set_fact:
#         current_hostname: "{{ item }}"
#       loop: "{{ hostname_list }}"

#     - name: Use hostname variable in another task
#       debug:
#         msg: "Processing hostname: {{ current_hostname }}"
- name: Include variables from var.yml
  include_vars:
    file: vars/var.yml

- name: Use variables from var.yml
  debug:
    var: hostname_list

